// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ianylbuallxrimlgqzbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhbnlsYnVhbGx4cmltbGdxemJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NTAxOTEsImV4cCI6MjA1NTMyNjE5MX0.GeDE5eWXPHJ350Y7_t5OeMh2bVn15310E30BOuKCRjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);